package crud;

import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;

import modelo.Astronauta;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erasmo
 */
@SuppressWarnings("serial")
public class AstronautaCreate2 extends javax.swing.JFrame {
	
	Astronauta novoAstronauta;

    public Astronauta getNovoAstronauta() {
		return novoAstronauta;
	}

	public void setNovoAstronauta(Astronauta novoAstronauta) {
		this.novoAstronauta = novoAstronauta;
	}

	/**
     * Creates new form AstronautaCreate
     */
    public AstronautaCreate2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        bLimpar = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        lPrimeiro_Nome = new javax.swing.JLabel();
        lNome_do_Meio = new javax.swing.JLabel();
        lSobrenome = new javax.swing.JLabel();
        lData_Nasc = new javax.swing.JLabel();
        lData_Falec = new javax.swing.JLabel();
        lCidade = new javax.swing.JLabel();
        lEstado = new javax.swing.JLabel();
        lPais = new javax.swing.JLabel();
        lBio = new javax.swing.JLabel();
        lBio_eng = new javax.swing.JLabel();
        lMissao1 = new javax.swing.JLabel();
        lMissao2 = new javax.swing.JLabel();
        lMissao3 = new javax.swing.JLabel();
        lMissao4 = new javax.swing.JLabel();
        lMissao5 = new javax.swing.JLabel();
        lMissao6 = new javax.swing.JLabel();
        lMissao7 = new javax.swing.JLabel();
        lMissao8 = new javax.swing.JLabel();
        lFoto = new javax.swing.JLabel();
        tfPrimeiro_Nome = new javax.swing.JTextField();
        tfNome_Do_Meio = new javax.swing.JTextField();
        tfSobrenome = new javax.swing.JTextField();
        tfData_Nasc = new javax.swing.JTextField();
        tfData_Falec = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        tfPais = new javax.swing.JTextField();
        tfFoto = new javax.swing.JTextField();
        tfBio = new javax.swing.JTextField();
        tfBio_eng = new javax.swing.JTextField();
        tfM1 = new javax.swing.JTextField();
        tfM2 = new javax.swing.JTextField();
        tfM3 = new javax.swing.JTextField();
        tfM4 = new javax.swing.JTextField();
        tfM5 = new javax.swing.JTextField();
        tfM6 = new javax.swing.JTextField();
        tfM7 = new javax.swing.JTextField();
        tfM8 = new javax.swing.JTextField();
        bSair = new javax.swing.JButton();
        lTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        bSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					bSalvarActionPerformed(evt);
				} catch (ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        lPrimeiro_Nome.setText("Primeiro Nome");

        lNome_do_Meio.setText("Nome do Meio");

        lSobrenome.setText("Sobrenome");

        lData_Nasc.setText("Data de Nascimento");

        lData_Falec.setText("Data de Falecimento");

        lCidade.setText("Cidade");

        lEstado.setText("Estado");

        lPais.setText("País");

        lBio.setText("Biografia");

        lBio_eng.setText("Bio Inglês");

        lMissao1.setText("Missão 1");

        lMissao2.setText("Missão 2");

        lMissao3.setText("Missão 3");

        lMissao4.setText("Missão 4");

        lMissao5.setText("Missão 5");

        lMissao6.setText("Missão 6");

        lMissao7.setText("Missão 7");

        lMissao8.setText("Missão 8");

        lFoto.setText("Foto");

        limpaCampos();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNome_do_Meio)
                                    .addComponent(lSobrenome))
                                .addGap(74, 74, 74)
                                .addComponent(tfNome_Do_Meio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lPais)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lEstado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lCidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lData_Falec)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                    .addComponent(tfData_Falec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lData_Nasc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lFoto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lPrimeiro_Nome)
                                .addGap(73, 73, 73)
                                .addComponent(tfPrimeiro_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(tfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lBio)
                            .addComponent(lBio_eng))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lMissao4)
                                    .addComponent(lMissao3)
                                    .addComponent(lMissao2)
                                    .addComponent(lMissao1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfM1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(tfM2)
                                    .addComponent(tfM3)
                                    .addComponent(tfM4))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lMissao6)
                                    .addComponent(lMissao5)
                                    .addComponent(lMissao7)
                                    .addComponent(lMissao8))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfM5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(tfM6)
                                    .addComponent(tfM7)
                                    .addComponent(tfM8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBio_eng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                    .addComponent(tfBio, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lPrimeiro_Nome)
                                    .addComponent(tfPrimeiro_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNome_do_Meio)
                                    .addComponent(tfNome_Do_Meio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lSobrenome)
                                    .addComponent(tfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfBio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lData_Nasc)
                                    .addComponent(tfData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lBio_eng))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lData_Falec)
                                    .addComponent(tfData_Falec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lCidade)
                                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfBio_eng, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEstado)
                            .addComponent(lMissao1)
                            .addComponent(lMissao5)
                            .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfM5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPais)
                            .addComponent(lMissao2)
                            .addComponent(lMissao6)
                            .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfM6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lMissao3)
                            .addComponent(lMissao7)
                            .addComponent(lFoto)
                            .addComponent(tfFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfM7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lBio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lMissao4)
                        .addComponent(tfM8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lMissao8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLimpar)
                    .addComponent(bSalvar))
                .addContainerGap())
        );

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        lTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lTitulo.setText("Cadastro de Astronauta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bSair)
                .addGap(459, 459, 459))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(bSair)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>  
    
    @SuppressWarnings("null")
	protected void bSalvarActionPerformed(ActionEvent evt) throws ParseException {
		String primeiro_nome = tfPrimeiro_Nome.getText();
		String nome_do_meio = tfNome_Do_Meio.getText();
		String sobrenome = tfSobrenome.getText();
		String pais = tfPais.getText();
		String estado = tfEstado.getText();
		String cidade = tfCidade.getText();
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
	    java.util.Date dataN = format.parse(tfData_Nasc.getText());
	    java.sql.Date data_nasc =  new java.sql.Date(dataN.getTime()); 
	    java.util.Date dataF = format.parse(tfData_Nasc.getText());
		java.sql.Date data_falec = new java.sql.Date(dataF.getTime());
		String foto = tfFoto.getText();
		String sexo = tfSexo.getText();
		String bio = tfBio.getText();
		String bio_eng = tfBio_eng.getText();
		String m1 = tfM1.getText();
		String m2 = tfM2.getText();
		String m3 = tfM3.getText();
		String m4 = tfM4.getText();
		String m5 = tfM5.getText();
		String m6 = tfM6.getText();
		String m7 = tfM7.getText();
		String m8 = tfM8.getText();
		
		List<String> missao = null;
		missao.add(m1);
		missao.add(m2);
		missao.add(m3);
		missao.add(m4);
		missao.add(m5);
		missao.add(m6);
		missao.add(m7);
		missao.add(m8);
		
		int n_missoes = missao.size();
		
		Astronauta novoAstronauta = new Astronauta(
				primeiro_nome,
				nome_do_meio,
				sobrenome, 
				pais,
				estado,
				cidade,
				foto,
				sexo,
				bio,
				bio_eng,
				data_nasc,
				data_falec,
				missao,
				n_missoes,
				null
			);
		
		this.setNovoAstronauta(novoAstronauta);	
	}

	private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {  
    	
    	limpaCampos();
    	
    }

	/**
	 * Limpa os campos de texto
	 */
	public void limpaCampos() {
		tfPrimeiro_Nome.setText("");
    	tfNome_Do_Meio.setText("");
    	tfSobrenome.setText("");
    	tfData_Nasc.setText("");
    	tfData_Falec.setText("");
    	tfCidade.setText("");
    	tfEstado.setText("");
    	tfPais.setText("");
    	tfFoto.setText("");
    	tfBio.setText("");
    	tfSexo.setText("");
    	tfBio_eng.setText("");
    	tfM1.setText("");
    	tfM2.setText("");
    	tfM3.setText("");
    	tfM4.setText("");
    	tfM5.setText("");
    	tfM6.setText("");
    	tfM7.setText("");
    	tfM8.setText("");
	}  

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.exit(0);
    }   
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AstronautaCreate2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AstronautaCreate2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AstronautaCreate2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AstronautaCreate2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AstronautaCreate2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSalvar;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lBio;
    private javax.swing.JLabel lBio_eng;
    private javax.swing.JLabel lPrimeiro_Nome;
    private javax.swing.JLabel lNome_do_Meio;
    private javax.swing.JLabel lSobrenome;
    private javax.swing.JLabel lData_Nasc;
    private javax.swing.JLabel lData_Falec;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lPais;
    private javax.swing.JLabel lFoto;
    private javax.swing.JLabel lSexo;
    private javax.swing.JLabel lMissao1;
    private javax.swing.JLabel lMissao2;
    private javax.swing.JLabel lMissao3;
    private javax.swing.JLabel lMissao4;
    private javax.swing.JLabel lMissao5;
    private javax.swing.JLabel lMissao6;
    private javax.swing.JLabel lMissao7;
    private javax.swing.JLabel lMissao8;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JTextField tfPrimeiro_Nome;
    private javax.swing.JTextField tfBio;
    private javax.swing.JTextField tfBio_eng;
    private javax.swing.JTextField tfNome_Do_Meio;
    private javax.swing.JTextField tfSobrenome;
    private javax.swing.JTextField tfData_Nasc;
    private javax.swing.JTextField tfData_Falec;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfPais;
    private javax.swing.JTextField tfFoto;
    private javax.swing.JTextField tfSexo;
    private javax.swing.JTextField tfM1;
    private javax.swing.JTextField tfM2;
    private javax.swing.JTextField tfM3;
    private javax.swing.JTextField tfM4;
    private javax.swing.JTextField tfM5;
    private javax.swing.JTextField tfM6;
    private javax.swing.JTextField tfM7;
    private javax.swing.JTextField tfM8;
    // End of variables declaration                   
}